// a sample grammar for testing
// use std::str::FromStr;
use crate::sysy::ast;

grammar;

match {
    // skip spaces and comments
    r"\s*" => {},
    r"//[^\n\r]*[\n\r]*" => {},
    // multiline comments, by Claude
    r"/\*[^*]*\*+(?:[^*/][^*]*\*+)*/" => {},
    _
}
// } else {
//     "int",
//     "void",
//     "return",
//     "break",
//     "continue",
//     "if",
//     "else",
//     "while"
// } else {
//     _,
// }

pub LitInt: ast::LitInt = {
    <s:r"[1-9][0-9]*"> => ast::LitInt(i32::from_str_radix(s, 10).unwrap()),
    <s:r"0[0-9]*"> => ast::LitInt(i32::from_str_radix(s, 8).unwrap()),
    <s:r"0[xX][0-9a-fA-F]+"> => ast::LitInt(i32::from_str_radix(&s[2..], 16).unwrap()),
};

// TODO: give precedence to keywords
pub Ident: ast::Ident = {
    <s:r"[a-zA-Z_][a-zA-Z0-9_]*"> => ast::Ident(s.to_string()),
}

pub Term: ast::Expr = {
    <n: LitInt> => ast::Expr::LitInt(n),
    <i: Ident> => ast::Expr::Ident(i),
    "(" <e: Expr> ")" => e,
    <name: Ident> "(" <mut args: (<Expr> ",")*> <arg: Expr?> ")" => {
        if let Some(arg) = arg {
            args.push(arg);
        }
        ast::Expr::FuncCall {
            name: name,
            args: args,
        }
    },
}

pub AllExpr: ast::Expr = {
    <e: Expr> => e,
}

pub Expr: ast::Expr = {
    // do not expand Term, or () cannot wrap expressions of lower precedence
    #[precedence(level="0")]
    <t: Term> => t,

    #[precedence(level="1")] #[assoc(side="left")]
    <e: Expr> "[" <i: AllExpr> "]" => ast::Expr::BinaryExpr {
        op: ast::BinaryOp::Index,
        lhs: Box::new(e),
        rhs: Box::new(i),
    },

    #[precedence(level="2")] #[assoc(side="right")]
    "+" <e: Expr> => ast::Expr::UnaryExpr{
        op: ast::UnaryOp::Pos,
        expr: Box::new(e),
    },

    "-" <e: Expr> => ast::Expr::UnaryExpr{
        op: ast::UnaryOp::Neg,
        expr: Box::new(e),
    },

    "!" <e: Expr> => ast::Expr::UnaryExpr{
        op: ast::UnaryOp::LNot,
        expr: Box::new(e),
    },

    #[precedence(level="3")] #[assoc(side="left")]
    <lhs: Expr> "*" <rhs: Expr> => ast::Expr::BinaryExpr{
        op: ast::BinaryOp::Mul,
        lhs: Box::new(lhs),
        rhs: Box::new(rhs),
    }.into(),

    <lhs: Expr> "/" <rhs: Expr> => ast::Expr::BinaryExpr{
        op: ast::BinaryOp::Div,
        lhs: Box::new(lhs),
        rhs: Box::new(rhs),
    }.into(),

    <lhs: Expr> "%" <rhs: Expr> => ast::Expr::BinaryExpr{
        op: ast::BinaryOp::Mod,
        lhs: Box::new(lhs),
        rhs: Box::new(rhs),
    }.into(),

    #[precedence(level="4")] #[assoc(side="left")]
    <lhs: Expr> "+" <rhs: Expr> => ast::Expr::BinaryExpr{
        op: ast::BinaryOp::Add,
        lhs: Box::new(lhs),
        rhs: Box::new(rhs),
    },

    <lhs: Expr> "-" <rhs: Expr> => ast::Expr::BinaryExpr{
        op: ast::BinaryOp::Sub,
        lhs: Box::new(lhs),
        rhs: Box::new(rhs),
    },

    #[precedence(level="6")] #[assoc(side="left")]
    <lhs: Expr> "<" <rhs: Expr> => ast::Expr::BinaryExpr{
        op: ast::BinaryOp::Lt,
        lhs: Box::new(lhs),
        rhs: Box::new(rhs),
    },

    <lhs: Expr> ">" <rhs: Expr> => ast::Expr::BinaryExpr{
        op: ast::BinaryOp::Gt,
        lhs: Box::new(lhs),
        rhs: Box::new(rhs),
    },

    <lhs: Expr> "<=" <rhs: Expr> => ast::Expr::BinaryExpr{
        op: ast::BinaryOp::Leq,
        lhs: Box::new(lhs),
        rhs: Box::new(rhs),
    },

    <lhs: Expr> ">=" <rhs: Expr> => ast::Expr::BinaryExpr{
        op: ast::BinaryOp::Geq,
        lhs: Box::new(lhs),
        rhs: Box::new(rhs),
    },

    #[precedence(level="7")] #[assoc(side="left")]
    <lhs: Expr> "==" <rhs: Expr> => ast::Expr::BinaryExpr{
        op: ast::BinaryOp::Eq,
        lhs: Box::new(lhs),
        rhs: Box::new(rhs),
    },

    <lhs: Expr> "!=" <rhs: Expr> => ast::Expr::BinaryExpr{
        op: ast::BinaryOp::Neq,
        lhs: Box::new(lhs),
        rhs: Box::new(rhs),
    },

    #[precedence(level="11")] #[assoc(side="left")]
    <lhs: Expr> "&&" <rhs: Expr> => ast::Expr::BinaryExpr{
        op: ast::BinaryOp::LAnd,
        lhs: Box::new(lhs),
        rhs: Box::new(rhs),
    },

    #[precedence(level="12")] #[assoc(side="left")]
    <lhs: Expr> "||" <rhs: Expr> => ast::Expr::BinaryExpr{
        op: ast::BinaryOp::LOr,
        lhs: Box::new(lhs),
        rhs: Box::new(rhs),
    },
}

pub BaseType: ast::BaseType = {
    "int" => ast::BaseType::Int,
    "void" => ast::BaseType::Void,
}

pub BlockItem: ast::BlockItem = {
    <s: Stmt> => ast::BlockItem::Stmt(s),
    <d: Decl> => ast::BlockItem::Decl(d),
}

pub Block: ast::Block = {
    "{" <items: BlockItem*> "}" => ast::Block(items),
}

pub Stmt: ast::Stmt = {
    <s: OpenStmt> => s,
    <s: ClosedStmt> => s,
}

pub OpenStmt: ast::Stmt = {
    "if" "(" <cond: Expr> ")" <s1: Stmt> => ast::Stmt::If(cond, Box::new(s1), Box::new(ast::Stmt::Empty)),
    "if" "(" <cond: Expr> ")" <s1: ClosedStmt> "else" <s2: OpenStmt> => ast::Stmt::If(cond, Box::new(s1), Box::new(s2)),
}

pub ClosedStmt: ast::Stmt = {
    "break" ";" => ast::Stmt::Break,
    "continue" ";" => ast::Stmt::Continue,
    "return" <e: Expr> ";" => ast::Stmt::Return(Some(e)),
    "return" ";" => ast::Stmt::Return(None),
    <e: Expr> ";" => ast::Stmt::Expr(e),
    <b: Block> => ast::Stmt::Block(Box::new(b)),
    <l: Expr> "=" <r: Expr> ";" => ast::Stmt::Assign(l, r),
    ";" => ast::Stmt::Empty,
    "if" "(" <cond: Expr> ")" <s1: ClosedStmt> "else" <s2: ClosedStmt> => ast::Stmt::If(cond, Box::new(s1), Box::new(s2)),
    "while" "(" <cond: Expr> ")" <s: ClosedStmt> => ast::Stmt::While(cond, Box::new(s)),
}

pub SingleDim: ast::Expr = {
    "[" <e: Expr> "]" => e,
}

pub InitExpr: ast::InitExpr = {
    <e: Expr> => ast::InitExpr::Scalar(e),
    "{" <mut es: (<InitExpr> ",")*> <e: InitExpr?> "}" => {
        if let Some(e) = e {
            es.push(e);
        }
        ast::InitExpr::Array(es)
    }
}

pub VarDef: ast::VarDef = {
    <name: Ident> <shape: SingleDim*> => ast::VarDef {
        name: name,
        shape: shape,
        init: None,
    },
    <name: Ident> <shape: SingleDim*> "=" <init: InitExpr> => ast::VarDef {
        name: name,
        shape: shape,
        init: Some(init),
    },
}

pub VarDecl: ast::VarDecl = {
    <t: BaseType> <mut vds: (<VarDef> ",")*> <vd: VarDef?> ";" => ast::VarDecl {
        base_ty: t,
        vars: {
            if let Some(vd) = vd {
                vds.push(vd);
            }
            vds
        }
    }
}

pub Decl: ast::Decl = {
    <v: VarDecl> => ast::Decl::Var(v),
    "const" <v: VarDecl> => ast::Decl::Const(v),
}

pub FuncParam: ast::FuncParam = {
    <t: BaseType> <name: Ident> <dims: ("[" <Expr?> "]")*> => ast::FuncParam {
        ty: t,
        name: name,
        dims: dims,
    },
}

pub FuncDef: ast::FuncDef = {
    <t: BaseType> <name: Ident> "(" <mut params: (<FuncParam> ",")*> <param: FuncParam?> ")" <b: Block> => ast::FuncDef{
        ret_ty: t,
        name: name,
        params: {
            if let Some(param) = param {
                params.push(param);
            }
            params
        },
        body: b,
    },
}

pub TransUnitItem: ast::TransUnitItem = {
    <f: FuncDef> => ast::TransUnitItem::FuncDef(f),
    <d: Decl> => ast::TransUnitItem::Decl(d),
}

pub TransUnit: ast::TransUnit = {
    <items: TransUnitItem*> => ast::TransUnit(items),
}
